config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"

  resources :todos

  resources :todos do
    member do
      get :clone
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todo_params)
      redirect_to @todo
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def clone
    @base = Todo.find(params[:id])
    @todo = @base.dup
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to todos_path, status: :see_other
  end

  private
    def todo_params
      params.require(:todo).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_index.html.erb
<fieldset>
  <legend><%= title %> (<%= records.count %>)</legend>
  <%= link_to 'New', new_path %>
  <% if records.count > 0 %>
    <table border="1">
      <thead>
        <%= render partial: thead %>
      </thead>

      <tbody>
        <% records.each do |record| %>
          <tr>
            <%= render partial: tr, locals: {record: record} %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h4>No record found</h4>
  <% end %>
</fieldset>

app/views/todos/_form.html.erb
<%= form_with model: todo do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% todo.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% todo.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/clone.html.erb
<fieldset>
  <legend>Clone <%= link_to @base.title, @base %></legend>
  <%= render "form", todo: @todo %>
</fieldset>

<%= link_to "Back", @todo %>

app/views/todos/edit.html.erb
<fieldset>
  <legend>Edit <%= @todo.title %> (<%= @todo.id %>)</legend>
  <%= render "form", todo: @todo %>
</fieldset>

<%= link_to "Back", @todo %>

app/views/todos/index.html.erb
<%= render partial: "shared/index", locals: {
  title: "Todos",
  records: @todos,
  new_path: new_todo_path,
  thead: "todos/table/thead",
  tr: "todos/table/tr",
} %>

app/views/todos/new.html.erb
<fieldset>
  <legend>New Todo</legend>
  <%= render "form", todo: @todo %>
</fieldset>

<%= link_to "Back", todos_path %>

app/views/todos/show.html.erb
<fieldset>
  <legend>Todo: <%= @todo.title %> (<%= @todo.id %>)</legend>
  <%= link_to 'Edit', edit_todo_path(@todo) %>
  | <%= link_to 'Clone', clone_todo_path(@todo) %>
  | <%= link_to "Destroy", todo_path(@todo),
    data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  <table border="1">
    <tbody>
      <tr>
        <th>Title</th>
        <td><%= @todo.title %></td>
      </tr>
      <tr>
        <th>Body</th>
        <td><%= @todo.body %></td>
      </tr>
      <tr>
        <th>Created at</th>
        <td><%= @todo.created_at %></td>
      </tr>
      <tr>
        <th>Updated at</th>
        <td><%= @todo.updated_at %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to "Back", todos_path %>
</fieldset>

app/views/todos/table/_thead.html.erb
<tr>
  <th>Id</th>
  <th>Title</th>
  <th>Created at</th>
  <th>Updated at</th>
  <th colspan="4">Actions</th>
</tr>

app/views/todos/table/_tr.html.erb
<td><%= link_to record.id, record %></td>
<td><%= record.title %></td>
<td><%= record.created_at %></td>
<td><%= record.updated_at %></td>
<td><%= link_to 'Show', record %></td>
<td><%= link_to 'Edit', edit_todo_path(record) %></td>
<td><%= link_to 'Clone', clone_todo_path(record) %></td>
<td><%= link_to "Destroy", record,
  data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }
%></td>